const translations = {
  zh: {
    brandName: "友联装修有限公司",
    brandSub: "Singapore Carpentry & Renovation",
    navServices: "服务",
    navCases: "案例",
    navProcess: "流程",
    navContact: "联系",
    callNow: "+65 9342 9984",
    heroEyebrow: "新加坡木工装修 · 20年经验",
    heroTitle: "把每一寸空间，做得耐用、顺手、好看。",
    heroText:
      "友联装修有限公司承接家庭与商户装修、木工定制、吊顶、水电、翻新及维修。免费上门量尺寸，安装到位，售后有跟进。",
    heroCall: "电话咨询",
    heroWhatsApp: "WhatsApp 预约量尺",
    factYears: "20年",
    factYearsText: "装修经验",
    factMeasure: "免费",
    factMeasureText: "上门量尺寸",
    factAfter: "售后",
    factAfterText: "维修保障",
    visualNoteTitle: "现场量尺 · 木作 · 水电配合",
    visualNoteText: "从设计沟通到安装收尾，一次安排清楚。",
    promiseOne: "免费上门量尺寸",
    promiseTwo: "免费安装安排",
    promiseThree: "家庭与商户均可承接",
    promiseFour: "包售后维修",
    servicesEyebrow: "Services",
    servicesTitle: "从木工到整屋翻新，一站式协调。",
    serviceCabinetTitle: "定制柜与收纳",
    serviceCabinetText: "厨房柜、衣柜、鞋柜、电视柜、展示柜、办公柜等，按空间尺寸定做。",
    serviceCeilingTitle: "吊顶、房门与空间造型",
    serviceCeilingText: "石膏板吊顶、灯槽、木饰面、房门制作以及安装、隔断与细节收口，保持简洁耐看。",
    serviceMEPTitle: "水电配合",
    serviceMEPText: "装修中的接水电、灯位、插座、厨房与卫生间基础配合，减少返工。",
    serviceRenoTitle: "家庭与商户装修",
    serviceRenoText: "住宅、办公室、店铺、餐饮与小型商业空间装修、翻新与维修。",
    casesEyebrow: "Case Types",
    casesTitle: "二十年经验里，最常做的装修场景。",
    caseHomeTag: "住宅翻新",
    caseHomeTitle: "客厅、厨房、吊顶与全屋柜体",
    caseHomeText: "适合 HDB、公寓与私人住宅，统一处理收纳、灯光、吊顶和水电细节。",
    caseCabinetTag: "木工定制",
    caseCabinetTitle: "任何柜子，按尺寸做",
    caseCabinetText: "从简单实用到隐藏灯带、玻璃门、开放格，按预算与使用习惯调整。",
    caseCommercialTag: "商户装修",
    caseCommercialTitle: "店铺、办公室与维修翻新",
    caseCommercialText: "关注工期、动线与耐用度，尽量减少营业或入住前的等待时间。",
    processEyebrow: "Process",
    processTitle: "沟通清楚，现场做稳。",
    processOneTitle: "电话或 WhatsApp 咨询",
    processOneText: "说明地址、空间类型、想做的项目与大概时间。",
    processTwoTitle: "免费上门量尺寸",
    processTwoText: "现场确认尺寸、结构、水电位置与安装条件。",
    processThreeTitle: "报价与施工安排",
    processThreeText: "根据材料、范围、工期与安装方式给出清楚报价。",
    processFourTitle: "安装与售后维修",
    processFourText: "施工收尾后保留售后联系，有问题可继续跟进维修。",
    contactEyebrow: "Contact",
    contactTitle: "需要量尺或报价，直接联系友联装修。",
    contactText: "欢迎发送现场照片、平面图或简单需求，我们会协助判断做法与下一步安排。",
    addressLabel: "地址",
    contactCTA: "WhatsApp 预约免费上门量尺",
    footerBrand: "友联装修有限公司",
    footerText: "新加坡木工、装修、翻新与售后维修。",
    backTop: "回到顶部",
  },
  en: {
    brandName: "You Lian Renovation Co., Ltd.",
    brandSub: "Singapore Carpentry & Renovation",
    navServices: "Services",
    navCases: "Cases",
    navProcess: "Process",
    navContact: "Contact",
    callNow: "+65 9342 9984",
    heroEyebrow: "Singapore carpentry renovation · 20 years of experience",
    heroTitle: "Durable, practical spaces built to fit every inch.",
    heroText:
      "You Lian Renovation provides home and commercial renovation, custom carpentry, ceilings, plumbing and electrical coordination, refurbishing, and repair. Free on-site measurement, installation support, and after-sales service included.",
    heroCall: "Call now",
    heroWhatsApp: "Book measurement on WhatsApp",
    factYears: "20 yrs",
    factYearsText: "Renovation experience",
    factMeasure: "Free",
    factMeasureText: "On-site measurement",
    factAfter: "After-sales",
    factAfterText: "Repair support",
    visualNoteTitle: "Site measurement · Carpentry · MEP coordination",
    visualNoteText: "From design discussion to installation, arranged clearly.",
    promiseOne: "Free on-site measurement",
    promiseTwo: "Free installation arrangement",
    promiseThree: "Homes and commercial spaces",
    promiseFour: "After-sales repair included",
    servicesEyebrow: "Services",
    servicesTitle: "One coordinated team for carpentry and renovation.",
    serviceCabinetTitle: "Custom Cabinets & Storage",
    serviceCabinetText: "Kitchen cabinets, wardrobes, shoe cabinets, TV consoles, display units, office storage, and more.",
    serviceCeilingTitle: "Ceilings, Doors & Interior Details",
    serviceCeilingText: "False ceilings, light troughs, wood finishes, room door fabrication and installation, partitions, and clean finishing details.",
    serviceMEPTitle: "Plumbing & Electrical",
    serviceMEPText: "Water and electrical points, lighting, sockets, kitchens, bathrooms, and renovation coordination.",
    serviceRenoTitle: "Home & Commercial Renovation",
    serviceRenoText: "Residential homes, offices, shops, F&B spaces, small commercial renovations, refurbishing, and repair.",
    casesEyebrow: "Case Types",
    casesTitle: "Common renovation scenarios shaped by two decades of experience.",
    caseHomeTag: "Home Renovation",
    caseHomeTitle: "Living rooms, kitchens, ceilings, and full-home cabinetry",
    caseHomeText: "For HDBs, condos, and private homes, coordinating storage, lighting, ceilings, and utility details.",
    caseCabinetTag: "Custom Carpentry",
    caseCabinetTitle: "Any cabinet, made to measure",
    caseCabinetText: "From simple storage to lighting, glass doors, and open shelves, adjusted to budget and daily use.",
    caseCommercialTag: "Commercial Renovation",
    caseCommercialTitle: "Shops, offices, repair, and refurbishing",
    caseCommercialText: "Focused on timeline, flow, and durability to reduce downtime before opening or moving in.",
    processEyebrow: "Process",
    processTitle: "Clear communication. Reliable site work.",
    processOneTitle: "Call or WhatsApp",
    processOneText: "Share the address, space type, renovation scope, and preferred timing.",
    processTwoTitle: "Free on-site measurement",
    processTwoText: "Confirm dimensions, structure, water and electrical positions, and installation conditions.",
    processThreeTitle: "Quotation & schedule",
    processThreeText: "Receive a clear quote based on material, scope, timeline, and installation method.",
    processFourTitle: "Installation & after-sales repair",
    processFourText: "After handover, repair support remains available for follow-up issues.",
    contactEyebrow: "Contact",
    contactTitle: "For measurement or quotation, contact You Lian Renovation.",
    contactText: "Send site photos, floor plans, or a simple requirement and we will help advise the next step.",
    addressLabel: "Address",
    contactCTA: "Book free measurement on WhatsApp",
    footerBrand: "You Lian Renovation Co., Ltd.",
    footerText: "Singapore carpentry, renovation, refurbishing, and after-sales repair.",
    backTop: "Back to top",
  },
};

const toggle = document.querySelector(".language-toggle");
let activeLang = localStorage.getItem("youLianLang") || "zh";

function setLanguage(lang) {
  activeLang = lang;
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (translations[lang][key]) {
      node.textContent = translations[lang][key];
    }
  });
  localStorage.setItem("youLianLang", lang);
}

toggle.addEventListener("click", () => {
  setLanguage(activeLang === "zh" ? "en" : "zh");
});

setLanguage(activeLang);
